spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      auto-commit: 'true'
      minimum-idle: 5
      maximum-pool-size: 1000
      pool-name: DatebookHikariCP
    url: jdbc:mysql://10.6.4.64:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    password: laiyifen123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    password: 123456
    lettuce:
      pool:
        max-active: 200
        min-idle: 8
        max-wait: 30
        max-idle: 8
      shutdown-timeout: 100
    host: '10.6.4.64'
    port: 6379
#    cluster:
#      nodes: '10.6.4.64:6379'
server:
  port: 8081

mybatis:
  type-aliases-package: org.marsken.plantform.infrastructure.dataobject
  configuration:
    map-underscore-to-camel-case: 'true'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: 'classpath*:mapper/*.xml'


######################### cros #########################
access-control-allow-origin: '*'